version: '3.8'
services:
  database:
    image: keinos/sqlite3:latest
    volumes:
      - db_data:/db/development.sqlite3
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chat_app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    env_file: .env
    environment:
      RAILS_ENV: development

volumes:
  gem_cache:
  node_modules:
  db_data:
